Fixed ODE errors
cyberbotics/webots-projects pull request #10
Opened 2021-07-05 14:20 UTC by mael25

Fixes #7

2021-07-05 14:21 UTC, mael25 commented
I couldn't reproduce the error message in #7, but replaced the `boundingObject` of the `Mesh` by primitives, which should fix the issue.

2021-07-06 15:32 UTC, mael25 commented
If someone gets the warning described in #7, could they confirm that this solves the issue?

2021-07-07 07:17 UTC, omichel requested changes
I would revert the change with the mass/density as it now makes it impossible to change the mass of the ConveyorStation without changing its size...

2021-07-07 07:17 UTC, omichel commented on projects/seronet-spawner/protos/ConveyorStationPlatform.proto
> +              }
Indentation looks wrong here:
```suggestion
            geometry Mesh {
              url "meshes/docking_element.obj"
            }
```

2021-07-07 08:34 UTC, mael25 commented
The mass of the children of the `ConveyorStation` is now such that the total mass corresponds exactly to the one defined by the user.

2021-07-07 08:43 UTC, omichel approved these changes
Yes, it looks way better like that.

2021-07-07 09:23 UTC, merged